---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

verifier:
  name: inspec
  format: progress

provisioner:
  name: chef_github
  chef_omnibus_url: "https://omnitruck.chef.io/install.sh"
  chef_omnibus_install_options: "-c current"
  github_owner: "chef"
  github_repo: "chef"
  ohai_refname: "master"
  refname: <%= %x(git rev-parse HEAD) %>
  client_rb:
    diff_disabled: true

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: base
    run_list:
      - recipe[base::default]
  - name: awesome_customers_ubuntu
    includes: [ubuntu-14.04, ubuntu-16.04]
    run_list:
      - recipe[awesome_customers_ubuntu_wrapper::default]
  - name: awesome_customers_rhel
    includes: [centos-6, centos-7]
    run_list:
      - recipe[awesome_customers_rhel_wrapper::default]
